# Generated by Django 5.0.2 on 2024-03-14 08:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_post_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_speciality', models.CharField(choices=[('MH', 'Mental Health'), ('HD', 'Heart Disease'), ('CV', 'Covid19'), ('IM', 'Immunization')], default='CV', max_length=2)),
                ('date_of_appointment', models.DateField(blank=True, default=datetime.date.today)),
                ('start_time', models.TimeField(blank=True, default=datetime.datetime(2024, 3, 14, 8, 15, 32, 357803, tzinfo=datetime.timezone.utc))),
                ('end_time', models.TimeField(blank=True)),
                ('doctor_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_of_appointment', '-start_time'],
                'indexes': [models.Index(fields=['-date_of_appointment', '-start_time'], name='account_app_date_of_04a58a_idx')],
            },
        ),
    ]
